version: '3.8'
services:
  neo4j:
    image: neo4j:5.28
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j-data:/data
  qdrant:
    image: qdrant/qdrant:v1.11.3
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  neo4j-data:
  qdrant-data:
  redis-data:

# Usage: docker-compose up; env USE_SQLITE=true for fallback (handled in code)